name: tslots
version: 1.0.0
config-version: 2
profile: tslots
model-paths:
  - models
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
models:
  tslots:
    staging:
      +materialized: table
      +schema: bronze
    intermediate:
      +materialized: table
      +schema: silver
      +post-hook: "ALTER TABLE {{ this }} ADD COLUMN id BIGSERIAL"
    marts:
      +materialized: table
      +schema: gold
target-path: target
